#!/usr/bin/env ruby

require 'json'
require 'net/http'
require 'net/https'
require 'optparse'

attachment = {
  :title => nil,
  :title_link => nil,
  :text  => nil,
  :color => "good",
  :fields => nil
}

payload = {
  :username     => ARGV[1]?ARGV[1]:"Deploy",
  :icon_emoji   => ARGV[2]?ARGV[2]:":deploy:",
  :text         => ARGV[0],
  :attachments  => nil,
}

uri = URI.parse(ENV["PG_TECH_HOOK"])

https = Net::HTTP.new(uri.host, uri.port)
https.use_ssl = true

request = Net::HTTP::Post.new(uri.request_uri)
request.form_data = { :payload => payload.to_json }

https.request(request)
